# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/blog.torresi.io_blogposts.yaml
- bases/blog.torresi.io_comments.yaml
- bases/blog.torresi.io_commentupvotes.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_blogposts.yaml
#- patches/webhook_in_comments.yaml
#- patches/webhook_in_commentupvotes.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CAINJECTION] patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_blogposts.yaml
#- patches/cainjection_in_comments.yaml
#- patches/cainjection_in_commentupvotes.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
